/**
 * @author Maksym Palii
 * @brief GPIO driver for ATmega644
 * @version 1.0
 * Inspired by Niklas Nilsson 
*/

#include "gpio.h"

void init_gpio(void)
{
    /**
     * Disable JTAG interface in order to make pins 2, 3, 4, 5 (Port C) as general purpose
     * see https://ww1.microchip.com/downloads/en/DeviceDoc/doc2593.pdf#G1.1375224
     */
    MCUCR |= _BV(JTD);
    MCUCR |= _BV(JTD);

    // Main pin configuration
    GPIO_SET_OUTPUT(_GPIO_UNUSED_01);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_02);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_03);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_04);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_05);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_06);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_07);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_08);

    GPIO_SET_OUTPUT(_GPIO_UNUSED_09);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_10);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_11);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_12);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_13);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_14);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_15);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_16);

    GPIO_SET_OUTPUT(_GPIO_UNUSED_17);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_18);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_19);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_20);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_21);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_22);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_23);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_24);

    GPIO_SET_OUTPUT(_GPIO_UNUSED_25);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_26);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_27);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_28);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_29);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_30);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_31);
    GPIO_SET_OUTPUT(_GPIO_UNUSED_32);
}
